// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCubiiBIq-9getX4bvSbCdSWFUCNggJbc0',
    appId: '1:704511975388:web:06913b56319ba1d501b919',
    messagingSenderId: '704511975388',
    projectId: 'automappregistration',
    authDomain: 'automappregistration.firebaseapp.com',
    storageBucket: 'automappregistration.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF74nAnmkUn5dKJy0fQnmJPjEG5xO-w3E',
    appId: '1:704511975388:android:6515517409d241f901b919',
    messagingSenderId: '704511975388',
    projectId: 'automappregistration',
    storageBucket: 'automappregistration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oAzcGaTmvHxemOIIq4Q6I2c_Fbb7PBs',
    appId: '1:704511975388:ios:89f12a2671270dda01b919',
    messagingSenderId: '704511975388',
    projectId: 'automappregistration',
    storageBucket: 'automappregistration.appspot.com',
    iosBundleId: 'com.example.automAppRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oAzcGaTmvHxemOIIq4Q6I2c_Fbb7PBs',
    appId: '1:704511975388:ios:53704a877ebbf37801b919',
    messagingSenderId: '704511975388',
    projectId: 'automappregistration',
    storageBucket: 'automappregistration.appspot.com',
    iosBundleId: 'com.example.automAppRegistration.RunnerTests',
  );
}
